// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/enter": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/subscribe": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/perfil": {
    params: {};
  };
  "/trocar-senha": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/enter" | "/login" | "/subscribe" | "/chat" | "/perfil" | "/trocar-senha";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/page/startPage.tsx": {
    id: "routes/page/startPage";
    page: "/enter";
  };
  "routes/services/loginService.tsx": {
    id: "routes/services/loginService";
    page: "/login";
  };
  "routes/services/subscribeService.tsx": {
    id: "routes/services/subscribeService";
    page: "/subscribe";
  };
  "routes/services/chatService.tsx": {
    id: "routes/services/chatService";
    page: "/chat";
  };
  "routes/services/profileService.tsx": {
    id: "routes/services/profileService";
    page: "/perfil";
  };
  "routes/services/changePasswordService.tsx": {
    id: "routes/services/changePasswordService";
    page: "/trocar-senha";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/page/startPage": typeof import("./app/routes/page/startPage.tsx");
  "routes/services/loginService": typeof import("./app/routes/services/loginService.tsx");
  "routes/services/subscribeService": typeof import("./app/routes/services/subscribeService.tsx");
  "routes/services/chatService": typeof import("./app/routes/services/chatService.tsx");
  "routes/services/profileService": typeof import("./app/routes/services/profileService.tsx");
  "routes/services/changePasswordService": typeof import("./app/routes/services/changePasswordService.tsx");
};